# proto-file: taskboard_spawning_service.proto
# proto-message: TaskboardSpawningServiceConfig
[type.googleapis.com/intrinsic.TaskboardSpawningServiceConfig] {
  # Standard YAML file path used instead of proto parameters
  config_file_path: "/opt/ros/overlay/install/share/taskboard_spawning_service/config/sample_config.yaml"
}
