[package.build.backend]
name = "pixi-build-ros"
version = "==0.3.3.20260113.c8b6a54"
channels = [
  "https://prefix.dev/pixi-build-backends",
  "robostack-kilted",
  "conda-forge",
]

[package.host-dependencies]
ros-kilted-rosidl-generator-rs = "*"
ros2-distro-mutex = "==0.13.0"

[package.build-dependencies]
ros-kilted-rosidl-generator-rs = "*"
